import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

import Card from "../components/Card";
import Banner from "../components/Banner";

import bakeriesData from "../data/bakeries.json";
import { fetchBakeries } from "../lib/bakery-store";

export async function getStaticProps(context) {
  console.log("Hi GetStaticProps");

  const bakeries = await fetchBakeries();

  return {
    props: {
      bakeries,
    },
  };
}

export default function Home(props) {
  const btnClickHandler = () => {
    console.log("Btn is clicked, Don't Worry");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Sweets Maven</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View shops nearby"
          btnClickHandler={btnClickHandler}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="Hero-Image"
          />
        </div>
        {props.bakeries.length > 0 && (
          <>
            <h2 className={styles.heading2}>Islamabad Stores</h2>
            <div className={styles.cardLayout}>
              {props.bakeries.map((bakery) => {
                return (
                  <Card
                    name={bakery.name}
                    address={bakery.location.address}
                    imgUrl={
                      bakery.imgUrl ||
                      "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                    }
                    href={`/bakeries/${bakery.fsq_id}`}
                    key={bakery.fsq_id}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
